doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            EmployeManagement:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/EmployeManagement/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\EmployeManagement\Domain\Model\Entity'
                alias: EmployeManagement

            LeaveManagement:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LeaveManagement/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\LeaveManagement\Domain\Model\Entity'
                alias: LeaveManagement

            AccessIdentity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/AccessIdentity/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\AccessIdentity\Domain\Model\Entity'
                alias: AccessIdentity
            
            Purchase:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Purchase/Infrastructure/Persistence/Mapping'
                prefix: 'App\Purchase\Domain\Model\Entity'
                alias: Purchase

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
